# Generated by Django 4.0.3 on 2022-06-07 17:38

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=255, validators=[quiz.models.validate_answer_text]),
        ),
    ]
